// app/layout.tsx (Server Component)
import { Metadata } from "next";
import { Providers } from "@/redux/provider";
import './globals.css'
import RootLayout from "./RootLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <RootLayout>{children}</RootLayout>
        </Providers>
      </body>
    </html>
  );
}
